[package]
name = "held_karp_rust"
version = "0.1.0"
authors = ["Chris Ward <acward96@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
rayon = "*"
rand = "*"
hashbrown = { version = "0.1.8", features = ["rayon"] }
